### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronix.benchmark#2]
The directories should be renamed:
 - TSDB_Chronix_Interface -> chronix-benchmark-chronix-impl
 - TSDB_Graphite-Interface -> chronix-benchmark-graphite-impl
 - DatebaseInterface -> chronix-benchmark-interface
 - ...

**Comment by mcqueentc** [comment]
done

**Comment by FlorianLautenschlager** [comment]
Just write "fixes #3" in the commit message or the PR description to close the issue with a commit.
